# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your humble servant
email: sagenoff@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Website to play around with and re-aquaint myself with html/css/javascript/etc.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sagcats.github.io" # the base hostname & protocol for your site
twitter_username: sagcats
github_username:  sagcats

# Build settings
markdown: kramdown
